ocodista/trampar-de-casa

apps/web/domains/landing-page/HowItWorks.tsx
fixes a minor typo in domains/landing-page/HowItWorks.tsx
=> bug: fixes minor typo in landing page

README.md
In this PR I make some changes to the task list on README
Using
```md
````
instead of:
```md
[ ] Task
```
=> fix: task list on README

apps/web/app/layout.tsx, apps/web/domains/landing-page/Values.tsx
This PR underlines the link added in https://github.com/ocodista/trampar-de-casa/pull/15 for better clarity.
=> feat: Underline contribution link

README.md, apps/web/domains/landing-page/FAQ.tsx, apps/web/domains/landing-page/HowItWorks.tsx
- Add instructions to run the application locally.
- Fix hour format and related text.
=> Add "getting started" section to README

.husky/pre-commit, package.json, yarn.lock
#39
Adds husky and lint-staged to  lint staged files as a pre-commit hook
Currently just blocks the commit on linting errors - could potentially be configured to auto format instead
=> Lint staged

apps/web/app/not-found.tsx
404 not found page #57 
- Link component from next to return to main page
- full responsive page
preview:
=> feat: not-found page

README.md
#54
Shields generated with:
- https://shields.io/
- [Vercel badge](https://github.com/datejer/vercel-badge)
Is this ok or is there anything else we would like done different?
Preview of shields:
=> add shields, updated local dev section

apps/web/app/landing-page/Header.tsx, apps/web/app/landing-page/HowItWorks.tsx, apps/web/app/landing-page/Values.tsx, apps/web/app/landing-page/hero/Hero.tsx, apps/web/app/layout.tsx, apps/web/app/page.tsx
Lighthouse and Axe extensions were used to run an audit by static analyzing the code and generating accessibility reports. The issues found were fixed by the changes described below.
- Fix document language attribute to `pt-BR`
- Add `main` landmark to the page structure
- Fix the color contrast ratio between texts and backgrounds
- Add alternative text to images
**Before:**
- Axe
- Lighthouse
**Now:**
- Axe
- Lighthouse
https://www.w3.org/TR/WCAG21/#language-of-page
https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11.html
https://www.w3.org/TR/WCAG21/#contrast-minimum
=> Accessibility improvements

apps/web/app/components/ui/ScrollToTopButton.tsx, apps/web/app/page.tsx, yarn.lock
#76
Adds scroll to top button.  Styling is WIP
Preview:
=> feat: scroll to top button

apps/web/app/components/PartnerCompanies.tsx, apps/web/app/landing-page/Hero.tsx
1. Partnership coupon for community
2. Resized and realigned for mobile responsiveness
=> chore: Partnership coupon design

apps/web/app/components/ui/button.tsx, apps/web/app/landing-page/ContributeDialog.tsx, apps/web/app/landing-page/SubscriberForm.tsx
=> add Dialog with Call-to-Action for Star on Repository

apps/web/app/landing-page/SubscriberForm.tsx
The ideal outer border-radius is calculated by the inner border-radius + the space in between them.
So, with the changes I made, it should look like the image below.
=> Fix border radius size

packages/shared/emails/ProfileEmail.tsx, packages/shared/src/email/sendProfileEmail.tsx
These changes only affect the content
To send emails with gif, I use the link of vercel branch preview. The PR #149 has merged and now we can use the production URL.
=> change profile template text | change send profile link subject | change gif url

apps/web/app/api/subscribers/[id]/route.ts, packages/analytics/src/events.ts
In this PR I created a new event called `ProfileChanged`. When a subscriber updates your info this event is called.
=> tracking profile updates

apps/web/app/components/AutoComplete.tsx, apps/web/app/components/FilteredSelections.tsx
The skills field has a super simple filter, I implemented a more useful filter.
=> Improve search on skills component

apps/auto-email-sender/Profiling.md, apps/auto-email-sender/email-pre-renderer/src/Header.tsx, turbo.json
This PR has the changes about the last email sent (2023/11/01)
=> weekly release 2023-11-01

apps/web/app/components/Header.tsx
This PR resolves the issue of the mobile menu appearing on large screens, as shown below.
The expected behavior is for the mobile menu to be hidden on large screens, **even** when the "isMobileMenuOpen" state is 'true.'
In addition, this PR includes the following refactorings:
- Removal of redundant tailwind classes and consolidation into a single class.
- Replacement of the <a> tags with the Next.js Link component.
_The changes ensure that the mobile menu behaves correctly on large screens and improve code maintainability by eliminating repetitive classes and adopting the Link component for better navigation. It Enhances the user experience and code quality._
=> Refactor: header component

apps/web/app/landing-page/SubscribersCount.tsx, apps/web/app/page.tsx
In this Pr we back with page revalidate
=> add cache on landing page

README-en.md, README.md
With the actual events, having a README-en is an excellent idea to help improve contributions for Brazilian devs and all devs worldwide.
=> Creating a new README.md in English version.

apps/web/app/layout.tsx
This PR removes a console warning from the logs about the metadataBase url.
=> add metadataBase

README.md, apps/web/.env.example, apps/web/app/not-found.tsx, package.json, packages/db/package.json, turbo.json, yarn.lock
In this PR we remove Prisma and simplify the way to run a local instance of supabase.
=> Improve dev instructions

apps/auto-email-sender/Profiling.md, apps/auto-email-sender/email-pre-renderer/src/renderHeader.tsx
In this branch, I make changes for weekly sending and register the time of the execution of services
=> weekly release 2023-12-06

apps/auto-email-sender/email-pre-renderer/src/renderHeader.tsx
In this PR i change Header message of openings email template
=> weekly release 2023-12-27

scripts/auto-email-sender-setup.sh
In this PR i checkout main branch and make a pull for update repository
=> improve `auto-email-sender-setup.sh` script

.github/workflows/supabase-migration.yml
Fix command on supabase action
=> fix supabase action

.github/workflows/supabase-migration.yml
set working directory with supabase config of project
=> fix: set working directory

apps/web/app/blog/entrevistas/ArticleHeader.tsx, apps/web/app/blog/entrevistas/layout.tsx
Change the route segment config to a valid file
=> fix blog visitors count

apps/web/vercel.json
The cron job was pointing to the wrong path.
=> fix cron route

.github/workflows/build-next.yml, .github/workflows/verify-image-build.yml
In this PR I created a backup image based on the version patch of `apps/web` version
=> create versioned image
